services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-skm-disdikbud
    restart: unless-stopped
    ports:
      - "6180:80"
    volumes:
      - ./storage:/app/storage
      - ./bootstrap/cache:/app/bootstrap/cache
      - ./.env:/app/.env
      - ./database:/app/database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
